version: "3.7"

networks:
  patroni_patroni:
    external: true

services:
 haproxy:
    image: haproxy-patroni
    networks:
      - patroni_patroni
    ports:
      - 5000:5000
      - 5001:5001
      - 7000:7000
    hostname: haproxy
    deploy:
      mode: replicated
      replicas: 2