version: "3.7"

networks:
  patroni2_patroni:
    external: true

services:
 haproxy:
    image: haproxy-patroni
    networks:
      - patroni2_patroni
    ports:
      - 5000:5000
      - 7000:7000
    hostname: haproxy
    deploy:
#      mode: global
      mode: replicated
      replicas: 3
      placement: 
        constraints: [node.hostname == docker-desktop]